# Build and publish snapshot package when pushed to master

name: Publish Snapshot

on:
  workflow_dispatch: # enable manual trigger
  push:
    branches: [ "master" ]
    paths-ignore: [ ".github/**" ]

env:
  JAVA_VERSION_TO_USE: '21'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 5

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Build and Publish
      run: mvn -B -U -P github -T 1C -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
